name: Build Flet to APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flet App and Export as Web
      run: |
        python main.py --web --output-dir=web

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Capacitor and create Android project
      run: |
        npm install -g @capacitor/cli
        npx cap init fletApp "com.example.fletapp" --web-dir=web
        npx cap add android

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
